// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountTokenUsageSummary = { lifetimeTokens: number | null, peakDailyTokens: number | null, longestRunningTurnSec: number | null, currentStreakDays: number | null, longestStreakDays: number | null, };
